Added Contributed Resources Preference Pane
osate/osate2 pull request #1935
Opened 2019-08-08 15:39 UTC by AaronGreenhouse

Fixed #1134

2019-09-10 15:34 UTC, AaronGreenhouse commented
Moved the documentation to a new "Advanced OSATE Features" document and out of the "Getting Started" guide.

Removed the old "Override AADL_Project" command from the UI.

Fixed the preference pane to not show the resource or platform prefix on the URIs.

2020-06-15 17:21 UTC, AaronGreenhouse commented
> 2. The layout and scrollability of the preference page could be improved. 

Agreed.  I had troubles getting the scroll pane to work right at the time, but I've since used it for something else and may have better luck now...

2020-06-22 19:23 UTC, AaronGreenhouse commented
Split the preference pane "in half" using a sash, and encapsulated the the top list in a scroll pane.  Things are still a little weird because Eclipse puts the entire preference pane into another scroll pane, and the scroll panes interact strangely with each other.

2020-09-10 18:52 UTC, AaronGreenhouse commented
Made more changes along the #1134 branch.  See the comments there.

2020-10-01 19:05 UTC, AaronGreenhouse commented
Merged Anna's viewer changes.  I think this is ready to go!

2020-10-05 17:22 UTC, AaronGreenhouse commented
Updated the help docs.

2020-10-06 15:41 UTC, joeseibel requested changes
There are a couple simple English mistakes in the help text. See line specific comments.

2020-10-06 15:41 UTC, joeseibel commented on core/org.osate.help/markdown/AdvancedOSATEFeatures.md
> +The overriding resource must have the same filename as the original resource; the selection dialog only shows those files in the workspace that have the same name.  The below selection dialog shows t
Too many articles. Either "the" or "a" should be removed and the html should be regenerated.

```suggestion
The overriding resource must have the same filename as the original resource; the selection dialog only shows those files in the workspace that have the same name.  The below selection dialog shows the replacement 
```

2020-10-06 15:41 UTC, joeseibel commented on core/org.osate.help/markdown/AdvancedOSATEFeatures.md
> +When a contributed resource is overridden, the tree marks it as such, and the URI shows the workspace URi of the overriding resource:
```suggestion
When a contributed resource is overridden, the tree marks it as such, and the URI shows the workspace URI of the overriding resource:
```

2020-10-08 18:28 UTC, lwrage approved these changes

2020-10-08 18:29 UTC, merged