1375 model statistics
osate/osate2 pull request #2421
Opened 2020-08-27 19:11 UTC by keh181

fixes #1375

2020-08-28 18:30 UTC, keh181 commented
Should be fixed now. I previously moved the projects into the analyses workspace in eclipse, but I guess not the files themselves, that's my bad.

2020-09-17 18:59 UTC, lwrage requested changes

2020-09-17 18:59 UTC, lwrage commented on analyses/org.osate.modelstats.ui/markdown/ModelStatistics.md
> +<img src="images/ModelLocation.PNG" width="600" height="200"/>
This file isn't found on Linux because the file system is cases sensitive. Change to "png"

2020-09-17 18:59 UTC, lwrage commented on analyses/org.osate.modelstats.ui/markdown/ModelStatistics.md
> +<img src="images/ModelStatistics.PNG" width="500" height="400"/>
same as above

2020-09-18 19:02 UTC, lwrage approved these changes

2020-09-18 19:47 UTC, merged