2427 flow latency csv formatting
osate/osate2 pull request #2479
Opened 2020-10-07 13:22 UTC by asazonova

Add a space before mode name and add quotes around the mode name for csv file (flow latency analysis)
fixes #2427

2020-10-07 13:23 UTC, asazonova commented
Lutz, let me know if you have any ideas on what needs to be done if the list of individual mode names is too long

2020-10-30 14:29 UTC, lwrage requested changes

2020-10-30 14:29 UTC, lwrage commented on core/org.osate.aadl2/src/org/osate/aadl2/util/Aadl2Util.java
> +				members = members + ", \"" + mode.getComponentInstancePath() + "\"";
This encloses each individual mode name in quotes not the list as a whole. Also, the quotes only need to be added in the CSV report.

2020-11-03 14:13 UTC, lwrage approved these changes

2020-11-03 16:58 UTC, merged