Add icon for flow implementation. Display proper icon based on selected
osate/osate2 pull request #2480
Opened 2020-10-07 21:24 UTC by asazonova

Add icon for flow implementation. Display proper icon based on selected specification implementation: display flow path, sink or source

Fixes #2440 #2442

2020-10-07 21:26 UTC, asazonova commented
I also changed FlowSink.gif  file only because it shows up with white background in dark theme view (all others have transparent background, so they show up with black background). New file also has transparent background to match the others

2020-10-15 16:01 UTC, lwrage requested changes
Please add an icon for end to end flow.

2020-10-15 16:01 UTC, lwrage commented on core/org.osate.aadl2.edit/src/org/osate/aadl2/provider/FlowImplementationItemProvider.java
> +			return overlayImage(object, getResourceLocator().getImage("full/obj16/FlowSink"));
Add icons for flow source/sink implementation (and I above the line like flow implementation).

2020-10-15 16:01 UTC, lwrage commented on core/org.osate.aadl2.edit/src/org/osate/aadl2/provider/FlowImplementationItemProvider.java
>  		return overlayImage(object, getResourceLocator().getImage("full/obj16/FlowImplementation"));
For consistency name this file FlowPathImplementation.gif

2020-10-27 16:23 UTC, lwrage approved these changes

2020-10-27 16:26 UTC, lwrage commented
This PR doesn't fix #2442 because the labels are still either _Flow Specification_ or _Flow Implementation_. I'll merge it to close #2440 and move #2442 back to "Next".

2020-10-27 16:27 UTC, merged