Graphical editor cleanup
osate/osate2 pull request #2684
Opened 2021-07-13 15:18 UTC by philip-alldredge

Fix for various spot bugs issues and schema documentation.

2021-07-13 15:40 UTC, RyanMcilnay requested changes

2021-07-13 15:40 UTC, RyanMcilnay commented on ge/org.osate.ge.gef.ui/src/org/osate/ge/gef/ui/editor/AgeEditor.java
> +				throw new AgeGefRuntimeException("diagram file is nulll");
null is misspelled

2021-07-13 15:47 UTC, philip-alldredge commented on ge/org.osate.ge.gef.ui/src/org/osate/ge/gef/ui/editor/AgeEditor.java
> +				throw new AgeGefRuntimeException("diagram file is nulll");
Fixed

2021-07-13 16:01 UTC, RyanMcilnay submitted a review, later dismissed

2021-07-14 14:02 UTC, RyanMcilnay approved these changes

2021-07-14 14:04 UTC, merged